"""initial schema

Revision ID: 9a0fddae8644
Revises: 
Create Date: 2026-04-14 17:03:30.759247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a0fddae8644'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_idempotency_expires', 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('kakao_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'customer')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kakao_id')
    )
    op.create_table('stores',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_owner_id'), 'stores', ['owner_id'], unique=False)
    op.create_table('groups',
    sa.Column('public_id', sa.String(length=12), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('type', sa.String(length=20), server_default='reservation', nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('remaining_qty', sa.Integer(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'closed', 'pickup_ready', 'completed', 'cancelled')", name='ck_groups_status'),
    sa.CheckConstraint("type IN ('reservation', 'group_buy', 'pickup')", name='ck_groups_type'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_groups_closes_at', 'groups', ['closes_at'], unique=False, postgresql_where=sa.text("status = 'open'"))
    op.create_index('idx_groups_store_status', 'groups', ['store_id', 'status'], unique=False)
    op.create_table('store_members',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'staff')", name='ck_store_members_role'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'user_id', name='uq_store_members_store_user')
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'store_id', name='uq_subscriptions_user_store')
    )
    op.create_index('idx_subs_store', 'subscriptions', ['store_id'], unique=False, postgresql_where=sa.text('unsubscribed_at IS NULL'))
    op.create_index('idx_subs_user', 'subscriptions', ['user_id'], unique=False, postgresql_where=sa.text('unsubscribed_at IS NULL'))
    op.create_table('group_pickup_slots',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pickup_slots_group', 'group_pickup_slots', ['group_id'], unique=False)
    op.create_table('inventory_holds',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('portone_payment_id', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'converted', 'expired')", name='ck_inventory_holds_status'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_holds_active_user_group', 'inventory_holds', ['user_id', 'group_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_holds_expires', 'inventory_holds', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_holds_payment', 'inventory_holds', ['portone_payment_id'], unique=True, postgresql_where=sa.text('portone_payment_id IS NOT NULL'))
    op.create_table('orders',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='paid', nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=False),
    sa.Column('current_amount', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=200), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_slot_id', sa.UUID(), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_request_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('paid', 'confirmed', 'pickup_ready', 'picked_up', 'not_picked_up', 'cancelled')", name='ck_orders_status'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['pickup_slot_id'], ['group_pickup_slots.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_group', 'orders', ['group_id'], unique=False)
    op.create_index('idx_orders_group_user_active', 'orders', ['group_id', 'user_id'], unique=True, postgresql_where=sa.text("status IN ('paid', 'confirmed', 'pickup_ready')"))
    op.create_index('idx_orders_payment', 'orders', ['payment_id'], unique=True, postgresql_where=sa.text('payment_id IS NOT NULL'))
    op.create_index('idx_orders_store_status', 'orders', ['store_id', 'status'], unique=False)
    op.create_index('idx_orders_user', 'orders', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), server_default='inapp', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("channel IN ('inapp', 'sms', 'email')", name='ck_notifications_channel'),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed', 'cancelled')", name='ck_notifications_status'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_dedupe', 'notifications', ['dedupe_key'], unique=True, postgresql_where=sa.text("dedupe_key IS NOT NULL AND status != 'cancelled'"))
    op.create_index('idx_notif_pending', 'notifications', ['scheduled_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('idx_notif_user', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text("status IN ('sent', 'pending')"))
    op.create_table('order_adjustments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Integer(), nullable=False),
    sa.Column('refund_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('refund_payment_id', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('requested_by', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("refund_status IN ('pending', 'completed', 'failed')", name='ck_order_adjustments_refund_status'),
    sa.CheckConstraint("requested_by IN ('customer', 'owner', 'system')", name='ck_order_adjustments_requested_by'),
    sa.CheckConstraint("type IN ('quantity_reduce', 'full_cancel', 'admin_cancel', 'system_cancel')", name='ck_order_adjustments_type'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adjustments_order', 'order_adjustments', ['order_id'], unique=False)
    op.create_index('idx_adjustments_refund', 'order_adjustments', ['refund_status'], unique=False, postgresql_where=sa.text("refund_status = 'pending'"))
    op.create_table('order_events',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("actor_type IN ('customer', 'owner', 'system')", name='ck_order_events_actor_type'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_order', 'order_events', ['order_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_order', table_name='order_events')
    op.drop_table('order_events')
    op.drop_index('idx_adjustments_refund', table_name='order_adjustments', postgresql_where=sa.text("refund_status = 'pending'"))
    op.drop_index('idx_adjustments_order', table_name='order_adjustments')
    op.drop_table('order_adjustments')
    op.drop_index('idx_notif_user', table_name='notifications', postgresql_where=sa.text("status IN ('sent', 'pending')"))
    op.drop_index('idx_notif_pending', table_name='notifications', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('idx_notif_dedupe', table_name='notifications', postgresql_where=sa.text("dedupe_key IS NOT NULL AND status != 'cancelled'"))
    op.drop_table('notifications')
    op.drop_index('idx_orders_user', table_name='orders')
    op.drop_index('idx_orders_store_status', table_name='orders')
    op.drop_index('idx_orders_payment', table_name='orders', postgresql_where=sa.text('payment_id IS NOT NULL'))
    op.drop_index('idx_orders_group_user_active', table_name='orders', postgresql_where=sa.text("status IN ('paid', 'confirmed', 'pickup_ready')"))
    op.drop_index('idx_orders_group', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_holds_payment', table_name='inventory_holds', postgresql_where=sa.text('portone_payment_id IS NOT NULL'))
    op.drop_index('idx_holds_expires', table_name='inventory_holds', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('idx_holds_active_user_group', table_name='inventory_holds', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('inventory_holds')
    op.drop_index('idx_pickup_slots_group', table_name='group_pickup_slots')
    op.drop_table('group_pickup_slots')
    op.drop_index('idx_subs_user', table_name='subscriptions', postgresql_where=sa.text('unsubscribed_at IS NULL'))
    op.drop_index('idx_subs_store', table_name='subscriptions', postgresql_where=sa.text('unsubscribed_at IS NULL'))
    op.drop_table('subscriptions')
    op.drop_table('store_members')
    op.drop_index('idx_groups_store_status', table_name='groups')
    op.drop_index('idx_groups_closes_at', table_name='groups', postgresql_where=sa.text("status = 'open'"))
    op.drop_table('groups')
    op.drop_index(op.f('ix_stores_owner_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_table('users')
    op.drop_index('idx_idempotency_expires', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
